FROM python:3.9-alpine
ENV PYTHONUNBUFFERED 1
ADD ./config/requirements.txt /
RUN apk update
RUN apk add --virtual .build-deps 
RUN apk add --virtual libressl-dev python3-dev ssmtp
RUN apk add --virtual libc-dev g++ gcc libxslt-dev libffi-dev rust
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt
RUN mkdir /src
WORKDIR /src
